# -*- coding: utf-8 -*-
"""Q3 AI LAB TEST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K-FYXhrXI9pJ-vKjW2keUGwQU9z9TwBu
"""

import streamlit as st
import torch
import torchvision.models as models
import torchvision.transforms as transforms
import torch.nn.functional as F
from PIL import Image
import requests
import pandas as pd

# -------------------------------
# Page Configuration
# -------------------------------
st.set_page_config(
    page_title="Live Image Classifier",
    layout="centered"
)

st.title("🧠 Live Image Classification App")
st.caption("Powered by Pretrained ResNet-18 (ImageNet)")

# -------------------------------
# Step 1: Device setup
# -------------------------------
device = torch.device("cpu")

# -------------------------------
# Step 2: Load ImageNet labels
# -------------------------------
LABELS_URL = "https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt"
@st.cache_data
def load_labels(url):
    response = requests.get(url)
    return response.text.splitlines()

imagenet_labels = load_labels(LABELS_URL)

# -------------------------------
# Step 3: Load pretrained model
# -------------------------------
@st.cache_resource
def load_model():
    model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
    model.eval()
    return model

model = load_model().to(device)

# -------------------------------
# Step 4: Image preprocessing
# -------------------------------
transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# -------------------------------
# Step 5: Capture image
# -------------------------------
st.subheader("📷 Capture or Upload an Image")
captured_image = st.camera_input("Use your webcam to capture an image")

if captured_image:
    image = Image.open(captured_image).convert("RGB")

    st.image(image, caption="Input Image", use_container_width=True)

    input_tensor = transform(image)
    input_batch = input_tensor.unsqueeze(0).to(device)

    # -------------------------------
    # Step 6: Prediction
    # -------------------------------
    with torch.no_grad():
        logits = model(input_batch)

    probs = F.softmax(logits.squeeze(), dim=0)

    top_probs, top_indices = torch.topk(probs, k=5)

    results = pd.DataFrame({
        "Class": [imagenet_labels[i] for i in top_indices],
        "Confidence": (top_probs * 100).cpu().numpy()
    })

    # -------------------------------
    # Display Results
    # -------------------------------
    st.subheader("🔎 Top-5 Classification Results")
    st.dataframe(results, use_container_width=True)

    st.bar_chart(
        results.set_index("Class"),
        horizontal=True
    )

    best_class = results.iloc[0]["Class"]
    best_confidence = results.iloc[0]["Confidence"]

    st.success(
        f"🎯 Best Prediction: **{best_class}** with **{best_confidence:.2f}% confidence**"
    )

    st.info(
        "Confidence scores are derived using the Softmax function, "
        "which converts raw model outputs into probabilities."
    )